CREATE TYPE "AdminRole" AS ENUM ('SUPPORT', 'OPERATIONS', 'FINANCE', 'SUPERADMIN');
CREATE TYPE "DisputeStatus" AS ENUM ('OPEN', 'INVESTIGATING', 'WAITING', 'RESOLVED');
CREATE TYPE "DisputeResolution" AS ENUM ('REFUND', 'PARTIAL_REFUND', 'CREDIT', 'REJECTED', 'OTHER', 'TEAMMATE_NO_SHOW');
CREATE TYPE "SanctionType" AS ENUM ('WARNING', 'TEMP_SUSPENSION', 'BAN');
CREATE TYPE "SanctionStatus" AS ENUM ('ACTIVE', 'EXPIRED', 'REVOKED');
ALTER TABLE "User" ADD COLUMN "adminRole" "AdminRole";
CREATE TABLE "AdminAuditLog" ("id" TEXT NOT NULL,"actorId" TEXT,"action" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT,"reason" TEXT,"before" JSONB,"after" JSONB,"ipAddress" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AdminAuditLog_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AdminAuditLog_createdAt_idx" ON "AdminAuditLog"("createdAt");
CREATE INDEX "AdminAuditLog_actorId_createdAt_idx" ON "AdminAuditLog"("actorId","createdAt");
CREATE INDEX "AdminAuditLog_entityType_entityId_idx" ON "AdminAuditLog"("entityType","entityId");
CREATE TABLE "Dispute" ("id" TEXT NOT NULL,"orderId" TEXT,"openedById" TEXT NOT NULL,"openedByRole" "Role" NOT NULL,"assigneeId" TEXT,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"status" "DisputeStatus" NOT NULL DEFAULT 'OPEN',"resolution" "DisputeResolution","resolutionNote" TEXT,"amountEUR" DECIMAL(10,2),"resolvedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Dispute_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Dispute_status_updatedAt_idx" ON "Dispute"("status","updatedAt"); CREATE INDEX "Dispute_orderId_idx" ON "Dispute"("orderId"); CREATE INDEX "Dispute_openedById_idx" ON "Dispute"("openedById");
CREATE TABLE "DisputeNote" ("id" TEXT NOT NULL,"disputeId" TEXT NOT NULL,"authorId" TEXT NOT NULL,"internal" BOOLEAN NOT NULL DEFAULT true,"body" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DisputeNote_pkey" PRIMARY KEY ("id"),CONSTRAINT "DisputeNote_disputeId_fkey" FOREIGN KEY ("disputeId") REFERENCES "Dispute"("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE INDEX "DisputeNote_disputeId_createdAt_idx" ON "DisputeNote"("disputeId","createdAt");
CREATE TABLE "TeammateSanction" ("id" TEXT NOT NULL,"teammateId" TEXT NOT NULL,"type" "SanctionType" NOT NULL,"status" "SanctionStatus" NOT NULL DEFAULT 'ACTIVE',"reason" TEXT NOT NULL,"internalNote" TEXT,"startsAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"endsAt" TIMESTAMP(3),"createdById" TEXT,"revokedById" TEXT,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TeammateSanction_pkey" PRIMARY KEY ("id"));
CREATE INDEX "TeammateSanction_teammateId_status_idx" ON "TeammateSanction"("teammateId","status"); CREATE INDEX "TeammateSanction_endsAt_idx" ON "TeammateSanction"("endsAt");
CREATE TABLE "AdminSession" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"ipAddress" TEXT,"userAgent" TEXT,"lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AdminSession_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "AdminSession_tokenHash_key" ON "AdminSession"("tokenHash"); CREATE INDEX "AdminSession_userId_revokedAt_idx" ON "AdminSession"("userId","revokedAt");
CREATE TABLE "LoginEvent" ("id" TEXT NOT NULL,"userId" TEXT,"email" TEXT NOT NULL,"successful" BOOLEAN NOT NULL,"suspicious" BOOLEAN NOT NULL DEFAULT false,"ipAddress" TEXT,"userAgent" TEXT,"reason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "LoginEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "LoginEvent_email_createdAt_idx" ON "LoginEvent"("email","createdAt"); CREATE INDEX "LoginEvent_userId_createdAt_idx" ON "LoginEvent"("userId","createdAt");
CREATE TABLE "RateLimitBucket" ("key" TEXT NOT NULL,"count" INTEGER NOT NULL DEFAULT 0,"resetAt" TIMESTAMP(3) NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "RateLimitBucket_pkey" PRIMARY KEY ("key")); CREATE INDEX "RateLimitBucket_resetAt_idx" ON "RateLimitBucket"("resetAt");
