import type { LanguageCode } from "@/lib/i18n";

const de: Record<string, string> = {
  "No one online":"Niemand online", "online":"online", "from":"ab", "mode":"Modus", "modes":"Modi",
  "Available now":"Jetzt verfügbar", "Typical wait":"Übliche Wartezeit", "teammates available now":"Mitspieler jetzt verfügbar", "All games":"Alle Spiele", "Choose your game":"Wähle dein Spiel", "Pick a game to see available teammates, modes, and pricing.":"Wähle ein Spiel und sieh verfügbare Mitspieler, Modi und Preise.", "teammate online right now":"Mitspieler ist gerade online", "teammates online right now":"Mitspieler sind gerade online", "Search games...":"Spiele durchsuchen…", "No games match":"Keine passenden Spiele für",
  "Account":"Konto", "Account menu":"Kontomenü", "My profile":"Mein Profil", "Go to dashboard":"Zum Dashboard", "Quick access":"Schnellzugriff",
  "Orders & sessions":"Bestellungen & Sessions", "Chat overview":"Chat-Übersicht", "Manage users":"Nutzer verwalten", "Manage teammates":"Mitspieler verwalten", "Log out":"Abmelden",
  "Product":"Produkt", "Games":"Spiele", "How it works":"So funktioniert’s", "Become a Teammate":"Mitspieler werden", "Company":"Unternehmen", "About":"Über uns", "Contact":"Kontakt", "Legal":"Rechtliches",
  "Terms of Service":"Nutzungsbedingungen", "Privacy Policy":"Datenschutz", "Refund Policy":"Erstattungsrichtlinie", "All rights reserved.":"Alle Rechte vorbehalten.",
  "Not affiliated with Riot Games, Epic Games, or any game publisher.":"Nicht mit Riot Games, Epic Games oder einem Spielepublisher verbunden.",
  "Checkout":"Kasse", "Your game":"Dein Spiel", "Group size":"Gruppengröße", "Subtotal":"Zwischensumme", "Processing fee":"Bearbeitungsgebühr", "Coupon":"Gutschein", "Remove coupon":"Gutschein entfernen", "Add a coupon":"Gutschein hinzufügen", "Total":"Gesamt",
  "How do you want to check out?":"Wie möchtest du fortfahren?", "You're logged in":"Du bist angemeldet", "Continue":"Weiter", "Not you? Log out":"Nicht du? Abmelden", "Email address":"E-Mail-Adresse", "Continue as guest":"Als Gast fortfahren", "or":"oder", "Log in / Register":"Anmelden / Registrieren",
  "Enter your email address to continue.":"Gib deine E-Mail-Adresse ein, um fortzufahren.", "That doesn't look like a valid email address.":"Das sieht nicht nach einer gültigen E-Mail-Adresse aus.",
  "Verify it's you":"Bestätige deine Identität", "Enter the six-digit code from your authenticator app.":"Gib den sechsstelligen Code aus deiner Authenticator-App ein.", "Log in to QUP.gg":"Bei QUP.gg anmelden", "Create your account":"Erstelle dein Konto", "Welcome back, pick up right where you left off.":"Willkommen zurück – mach einfach dort weiter, wo du aufgehört hast.", "Takes less than 30 seconds. No credit card required.":"Dauert weniger als 30 Sekunden. Keine Kreditkarte nötig.", "Continue with Discord":"Mit Discord fortfahren", "Continue with Google":"Mit Google fortfahren", "Username":"Nutzername", "Your in-game name":"Dein In-Game-Name", "Password":"Passwort", "Hide password":"Passwort ausblenden", "Show password":"Passwort anzeigen", "Authenticator code":"Authenticator-Code", "Remember me":"Angemeldet bleiben", "Please wait…":"Bitte warten…", "Verify & continue":"Bestätigen und weiter", "Log in":"Anmelden", "Create account":"Konto erstellen", "Back to login":"Zurück zur Anmeldung", "New here?":"Neu hier?", "Create an account":"Konto erstellen", "Already have an account?":"Du hast schon ein Konto?",
  "Payment method":"Zahlungsmethode", "Unavailable":"Nicht verfügbar", "No extra fee":"Keine Zusatzgebühr", "Card":"Karte", "Credits":"Guthaben", "Processing...":"Wird verarbeitet…", "Pay":"Bezahlen", "Change":"Ändern",
  "Session ended":"Session beendet", "You played for":"Du hast gespielt:", "charged automatically via PayPal.":"automatisch über PayPal abgerechnet.", "View my orders":"Meine Bestellungen ansehen", "PayPal auto-pay connected":"Automatische PayPal-Zahlung verbunden", "Keep playing, you're billed automatically for the time you use.":"Spiel einfach weiter – abgerechnet wird automatisch nur deine genutzte Zeit.", "Elapsed":"Vergangen", "Running total":"Aktueller Gesamtbetrag", "/ minute":"/ Minute", "End session & charge total":"Session beenden und abrechnen",
  "Refer a friend":"Freund empfehlen", "and you both get €5 session credit.":"und ihr erhaltet beide 5 € Session-Guthaben.", "Learn more":"Mehr erfahren", "Dismiss":"Schließen",
  "You're not logged in — checking out as a guest below, or log in first.":"Du bist nicht angemeldet – fahre unten als Gast fort oder melde dich zuerst an.",
  "Your balance:":"Dein Guthaben:", "loading…":"wird geladen…", "Not enough credits for this total — top up or choose another payment method.":"Dein Guthaben reicht nicht aus – lade es auf oder wähle eine andere Zahlungsmethode.",
  "Mode":"Modus", "Your details":"Deine Angaben", "In-game info":"In-Game-Daten", "Pay step":"Bezahlen", "Teammate joins":"Mitspieler tritt bei", "Checking out as logged-in user":"Bezahlung mit deinem angemeldeten Konto", "Checking out as guest":"Bezahlung als Gast", "Playing as":"Du spielst als",
  "We accept":"Wir akzeptieren", "rated sessions":"bewertete Sessions", "out of 5":"von 5",
  "Why QUP.gg":"Warum QUP.gg", "Why players choose us.":"Warum Spieler uns wählen.", "From click to game":"Vom Klick ins Spiel", "Five steps, about two minutes.":"Fünf Schritte, etwa zwei Minuten.",
  "256-bit SSL on every order":"256-Bit-SSL bei jeder Bestellung", "Full refund if we can't match you":"Volle Erstattung, wenn wir keinen Mitspieler finden", "Real people, no bots":"Echte Menschen, keine Bots",
  "Pick your mode":"Wähle deinen Modus", "Game, session type, how many teammates.":"Spiel, Session-Art und Anzahl der Mitspieler.", "We search":"Wir suchen", "Waves of teammates, seconds apart.":"Mitspieler werden in kurzen Wellen angefragt.", "Someone accepts":"Jemand nimmt an", "You see who, and their rank, before you play.":"Du siehst vor dem Spiel, wer angenommen hat und welchen Rang die Person hat.", "You play together":"Ihr spielt zusammen", "Your account, theirs. Nobody logs in as you.":"Jeder spielt mit dem eigenen Konto. Niemand meldet sich als du an.", "You rate it":"Du bewertest die Session", "The score is public and decides who gets booked next.":"Die Bewertung ist öffentlich und beeinflusst kommende Buchungen.",
  "The price you see is the price you pay":"Du bezahlst genau den angezeigten Preis", "No service fee at checkout, and nothing charged before a teammate takes your order.":"Keine Servicegebühr an der Kasse und keine Abbuchung, bevor ein Mitspieler deine Bestellung annimmt.", "Sessions from":"Sessions ab", "Added at checkout":"An der Kasse hinzugefügt", "Charged before a teammate accepts":"Vor Annahme durch einen Mitspieler berechnet", "Nothing":"Nichts", "Cancel free until matched":"Kostenlos stornieren, solange du nicht gematcht bist",
  "Tier-1 support":"Erstklassiger Support", "Real people who play these games. No bots, no copy-paste.":"Echte Menschen, die diese Spiele selbst spielen. Keine Bots, keine Textbausteine.", "Real-time updates":"Updates in Echtzeit", "Get notified the moment your teammate is ready.":"Du bekommst sofort Bescheid, sobald dein Mitspieler bereit ist.", "Powerful real-time chat":"Leistungsstarker Echtzeit-Chat", "Opens the moment you are matched — lanes and roles sorted before champion select.":"Öffnet sich direkt nach dem Match – klärt Lanes und Rollen vor der Champion-Auswahl.",
  "Refund policy":"Erstattungsrichtlinie", "Order chat":"Bestellchat", "Email":"E-Mail", "A teammate accepted your order":"Ein Mitspieler hat deine Bestellung angenommen", "just now · tap to open":"gerade eben · zum Öffnen tippen", "Ready when you are 👋 I’ll go mid, you take jungle?":"Ich bin bereit 👋 Ich gehe Mid, übernimmst du Jungle?", "Sounds good — queueing now":"Passt – ich starte jetzt die Queue", "Type a message…":"Nachricht schreiben…",
  "Verified player ratings":"Verifizierte Spielerbewertungen", "Reviews from real sessions.":"Bewertungen aus echten Sessions.", "ratings left after completed QUP.gg sessions.":"Bewertungen nach abgeschlossenen QUP.gg-Sessions.", "Verified":"Verifiziert", "Teammate":"Mitspieler", "out of 5 stars":"von 5 Sternen",
  "Talk to a person":"Sprich mit einem Menschen", "Support is staffed by people who play these games. No bots and no ticket that goes quiet for three days.":"Unser Support besteht aus Menschen, die diese Spiele selbst spielen. Keine Bots und kein Ticket, das tagelang unbeantwortet bleibt.", "Best for anything with an order number attached.":"Am besten für alles rund um eine Bestellnummer.", "Fastest during European evenings, and where teammates hang out.":"Am schnellsten an europäischen Abenden – und dort triffst du unsere Mitspieler.", "Join the server":"Server beitreten", "A live session":"Laufende Session", "Open your orders":"Deine Bestellungen öffnen", "What to expect":"Damit kannst du rechnen", "Send us a message":"Schreib uns eine Nachricht", "No account needed. Everything here goes to the same inbox as the address above.":"Du brauchst kein Konto. Deine Nachricht landet im selben Postfach wie E-Mails an die Adresse links.",
  "Become a teammate":"Mitspieler werden", "Get paid for the games you were going to play anyway.":"Verdiene Geld mit den Games, die du sowieso spielst.", "Go available when you sit down, take the orders that suit you, and get paid per session at the rate you accepted.":"Geh online, wenn du spielen möchtest, nimm passende Bestellungen an und werde pro Session zum angezeigten Preis bezahlt.", "Apply now":"Jetzt bewerben", "See what people book":"Beliebte Buchungen ansehen", "How it goes":"So läuft es ab", "What we need from you":"Was du mitbringen solltest", "Apply":"Bewerben", "Questions":"Fragen", "Start your application":"Bewerbung starten", "Four short steps, about two minutes.":"Vier kurze Schritte, etwa zwei Minuten.",
  "Your name":"Dein Name", "What is it about?":"Worum geht es?", "Order number (if you have one)":"Bestellnummer (falls vorhanden)", "Message":"Nachricht", "What happened, and what would fix it?":"Was ist passiert und wie können wir es lösen?", "Sending…":"Wird gesendet…", "Send message":"Nachricht senden", "Message sent":"Nachricht gesendet", "An order or refund":"Bestellung oder Erstattung", "Payments":"Zahlungen", "Becoming a teammate":"Mitspieler werden", "Press or partnership":"Presse oder Partnerschaft", "Something else":"Etwas anderes",
  "Guides, updates and better games.":"Guides, Updates und bessere Games.", "Short, practical reads about the games you play, the teammates you meet and how QUP.gg works behind the scenes.":"Kurze, praktische Artikel über deine Games, deine Mitspieler und darüber, wie QUP.gg funktioniert.", "Browse game categories":"Spielkategorien ansehen", "Latest":"Aktuell", "Latest articles":"Neueste Beiträge", "articles":"Beiträge", "Read article":"Artikel lesen", "Previous":"Zurück", "Next":"Weiter", "Page":"Seite", "of":"von", "Gaming blog":"Gaming-Blog", "Categories":"Kategorien", "Game categories":"Spielkategorien", "Find guides for your game.":"Finde Guides für dein Spiel.", "Every article belongs to a game or the general QUP.gg category. Pick what you actually want to read.":"Jeder Beitrag gehört zu einem Spiel oder zur allgemeinen QUP.gg-Kategorie. Wähle einfach, was dich interessiert.", "All articles":"Alle Beiträge", "View articles":"Beiträge ansehen", "In this article":"In diesem Beitrag", "A short read from QUP.gg.":"Ein kurzer Beitrag von QUP.gg.", "More in":"Mehr aus", "No published articles yet.":"Noch keine veröffentlichten Beiträge.", "No published articles in this category yet.":"In dieser Kategorie gibt es noch keine veröffentlichten Beiträge.",
};

const dictionaries: Partial<Record<LanguageCode, Record<string, string>>> = { de };
export function translatePhrase(language: LanguageCode, phrase: string) { return dictionaries[language]?.[phrase] ?? phrase; }
